## Mahalanobis Distance

In [69]:
import pandas as pd
import numpy.random as nr

import matplotlib.pyplot as plt

Iris = pd.read_csv('iris.csv')
Iris.drop(columns='Id', inplace= True, axis= 1)
Iris.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [70]:
Iris.describe()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

### Selecting Random data

In [133]:
SampleList = []
for i in range(3):
    SampleList.append(nr.randint(i*50, i*50+49))
SampleList

[40, 69, 125]

In [134]:
TestData = Iris.iloc[SampleList]
TrainData = Iris.drop(index=SampleList)
TrainData.drop(columns='Species', inplace= True)
TestData.drop(columns='Species', inplace= True)

TestData

C:\Users\Ayush\AppData\Local\Temp\ipykernel_21436\3259091296.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  TestData.drop(columns='Species', inplace= True)


SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
40             5.0           3.5            1.3           0.3
69             5.6           2.5            3.9           1.1
125            7.2           3.2            6.0           1.8

#### Calculating Mean

In [136]:
MeanVec = []
for i in range(3):
    MeanVec.append(TrainData[i*49: (i+1)*49].mean(axis=0, numeric_only=True))
    # print(MeanVec[-1])
MeanVec

[SepalLengthCm    5.006122
 SepalWidthCm     3.416327
 PetalLengthCm    1.467347
 PetalWidthCm     0.242857
 dtype: float64,
 SepalLengthCm    5.942857
 SepalWidthCm     2.775510
 PetalLengthCm    4.267347
 PetalWidthCm     1.330612
 dtype: float64,
 SepalLengthCm    6.575510
 SepalWidthCm     2.969388
 PetalLengthCm    5.542857
 PetalWidthCm     2.030612
 dtype: float64]

In [111]:
import numpy as np
MeanVec = np.array(MeanVec)
MeanVec

array([[5.058     , 3.418     , 1.532     , 0.268     ],
       [5.918     , 2.768     , 4.298     , 1.356     ],
       [6.60425532, 2.97021277, 5.56170213, 2.01276596]])

#### Subtacting mean

In [114]:
MeanSub = []
for i in range (3):
    for j in range (49):
        MeanSub.append(TrainData.iloc[i*49 + j] - MeanVec[i])

MeanSub = np.array(MeanSub)
MeanSub.shape
MeanSub

array([[ 0.042     ,  0.082     , -0.132     , -0.068     ],
       [-0.158     , -0.418     , -0.132     , -0.068     ],
       [-0.358     , -0.218     , -0.232     , -0.068     ],
       [-0.458     , -0.318     , -0.032     , -0.068     ],
       [-0.058     ,  0.182     , -0.132     , -0.068     ],
       [ 0.342     ,  0.482     ,  0.168     ,  0.132     ],
       [-0.458     , -0.018     , -0.132     ,  0.032     ],
       [-0.058     , -0.018     , -0.032     , -0.068     ],
       [-0.658     , -0.518     , -0.132     , -0.068     ],
       [-0.158     , -0.318     , -0.032     , -0.168     ],
       [ 0.342     ,  0.282     , -0.032     , -0.068     ],
       [-0.258     , -0.018     ,  0.068     , -0.068     ],
       [-0.258     , -0.418     , -0.132     , -0.168     ],
       [-0.758     , -0.418     , -0.432     , -0.168     ],
       [ 0.742     ,  0.582     , -0.332     , -0.068     ],
       [ 0.642     ,  0.982     , -0.032     ,  0.132     ],
       [ 0.342     ,  0.

In [140]:
Sigma = TrainData.cov()
Sigma
type(Sigma)
Sigma

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm       0.681896     -0.039780       1.265062      0.516587
SepalWidthCm       -0.039780      0.188256      -0.322517     -0.118635
PetalLengthCm       1.265062     -0.322517       3.101199      1.298755
PetalWidthCm        0.516587     -0.118635       1.298755      0.586300

In [138]:
Sigma = np.array(Sigma)
Sigma

array([[ 0.68189637, -0.03977961,  1.2650615 ,  0.51658699],
       [-0.03977961,  0.18825645, -0.32251747, -0.11863526],
       [ 1.2650615 , -0.32251747,  3.10119933,  1.29875454],
       [ 0.51658699, -0.11863526,  1.29875454,  0.58629951]])

In [143]:
SigInv = np.linalg.inv(Sigma)
SigInv

array([[ 10.1597557 ,  -6.63665674,  -7.23775326,   5.73823745],
       [ -6.63665674,  11.07626084,   6.52323714,  -6.36131906],
       [ -7.23775326,   6.52323714,  10.09390728, -14.66263015],
       [  5.73823745,  -6.36131906, -14.66263015,  27.84273527]])

In [146]:
MDsq = MeanSub.dot(SigInv.dot(MeanSub.T))
# print(MeanSub.T.shape)
# print(Sigma.shape)
# print(MeanSub.shape)

MDsq.shape

(147, 147)